### ISSUE TITLE
[Barcalona] REST API replies include stack traces

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/core-metadata#28]
Some of the REST endpoints in the core-metadata service return Java stack traces when errors occur, including NotFound and DataValidation errors.

The first can be seen by running querying the metadata service for a service which doesn't exist using curl command (**note**, you may need to change the hostname depending on your setup):

**$ curl -w "%{http_code}" http://localhost:48081/api/v1/deviceservice/name/no-such-device-service**

The second can be seen by trying to add a deviceservice which has no addressable or already exists (a service with that name is already registered), which can be seen by running the following curl command:

**$ curl -w "%{http_code}" -H 'Content-Type: application/json' -d '{"id":null,"created":0,"modified":0,"origin":666,"name":"tony-ds","method":"POST","protocol":"HTTP","address":"localhost","port":51,"path":"/api/v1/callback","publisher":null,"user":null,"password":null,"topic":null}' http://localhost:48081/api/v1/deviceservice**

Here's what the stack trace for the latter looks like:

Improper data:  Name is not unique: device-service-test

org.edgexfoundry.exception.controller.DataValidationException: Improper data:  Name is not unique: device-service-test at org.edgexfoundry.controller.impl.DeviceServiceControllerImpl.add(DeviceServiceControllerImpl.java:303)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:832)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:743)
at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:961)
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:895)
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967)

**Comment by tonyespy** [comment]
Turns out the inclusion of stack traces is controlled by a service property called print.stacktrace, which is enabled by default, and turned off explicitly in the docker images.  As I was running the core services from my snap, this value was still set to it's default.  I'm closing this...
